command_timeout = 5000

[aws]
disabled = true

[ruby]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 8

[package]
disabled = true

[nodejs]
format = '[$symbol($version )]($style)'

[docker_context]
format = '[ğŸ³ docker ](blue bold)'

[elixir]
symbol = 'ğŸ”® '
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[lua]
format = '[$symbol($version )]($style)'
